SELECT CHARTER.CHAR_TRIP, CHARTER.CHAR_DATE, CHARTER.CHAR_DESTINATION, CHARTER.CUS_CODE, CUS_FNAME & " " & CUS_INITIAL & " " & CUS_LNAME AS FULLNAME
FROM CHARTER, CUSTOMER
WHERE 
CHARTER.CUS_CODE = CUSTOMER.CUS_CODE
AND CUS_LNAME = "DUNNE";